/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogEditor.java
 *
 * Created on Jun 27, 2012, 8:32:36 PM
 */

package LevelEditor;

/**
 *
 * @author Jim
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;

public class DialogEditor extends javax.swing.JPanel
{
    private Editor editor;
    private JTextArea dlgTA;
    private JButton save;
    public String contents = "";
    /** Creates new form DialogEditor */
    public DialogEditor(Editor e)
    {
        initComponents();
        editor = e;
        this.setLayout(null);
        this.setSize(400, 500);

        JLabel label = new JLabel("Dialog");
        this.add(label);
        label.setBounds(0, 0, 100, 50);

        dlgTA = new JTextArea("");
        dlgTA.setAutoscrolls(true);
        dlgTA.setEditable(true);

        JScrollPane jsp = new JScrollPane(dlgTA);
        jsp.setBounds(0, 50, 350, 200);
        jsp.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        this.add(jsp);

        save = new JButton("Save Changes");
        this.add(save);
        save.setBounds(0, 260, 150, 40);

        save.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent e)
            {
                saveChanges();
            }
        });
    }

    private void saveChanges()
    {
        editor.setDialog(dlgTA.getText());
    }

    public void updateDialog(Dialogue d)
    {
        contents = "";
        
        for(int i = 0; i < d.getContents().size(); i++)
        {
            contents += d.getContents().get(i) + "\n";
        }

        dlgTA.setText(contents);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
