/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DoorPlacer.java
 *
 * Created on Jun 11, 2012, 8:51:25 PM
 */

package LevelEditor;

/**
 *
 * @author Jim
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JButton;

public class DoorPlacer extends javax.swing.JPanel
{
    private Editor editor;
    private JComboBox secLev;
    private JComboBox objLev;
    private JCheckBox isDark;
    private JButton save;

    public Door door = null;

    /** Creates new form DoorPlacer */
    public DoorPlacer(Editor e)
    {
        initComponents();
        editor = e;
        this.setLayout(null);
        this.setSize(400, 300);

        JLabel l1 = new JLabel("Doors");
        this.add(l1);
        l1.setBounds(0, 0, 100, 50);

        JLabel l2 = new JLabel("Security Level:");
        this.add(l2);
        l2.setBounds(0, 50, 100, 50);

        Integer[] seclvs = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, -1};
        secLev = new JComboBox(seclvs);
        this.add(secLev);
        secLev.setBounds(100, 50, 50, 50);

        JLabel l3 = new JLabel("Objective Level:");
        this.add(l3);
        l3.setBounds(0, 110, 100, 50);

        Integer[] olevs = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25};
        objLev = new JComboBox(olevs);
        this.add(objLev);
        objLev.setBounds(100, 110, 50, 50);

        isDark = new JCheckBox("Dark looking in?");
        this.add(isDark);
        isDark.setBounds(0, 170, 150, 50);

        save = new JButton("Save Changes");
        this.add(save);
        save.setBounds(0, 230, 150, 50);

        secLev.addActionListener(new ActionListener()
        {

            public void actionPerformed(ActionEvent e)
            {
                secLev();
            }

        });

        objLev.addActionListener(new ActionListener()
        {

            public void actionPerformed(ActionEvent e)
            {
                objLev();
            }

        });

        isDark.addActionListener(new ActionListener()
        {

            public void actionPerformed(ActionEvent e)
            {
                dark();
            }

        });

        save.addActionListener(new ActionListener()
        {

            public void actionPerformed(ActionEvent e)
            {
                save();
            }

        });

    }

    private void secLev()
    {
        if (secLev.getSelectedIndex() <= 10)
        {
            editor.selectedPayload.secLev = secLev.getSelectedIndex();
        }
        else
        {
            editor.selectedPayload.secLev = -1;
        }
    }
    
    private void objLev()
    {
        editor.selectedPayload.objLev = objLev.getSelectedIndex();
    }

    private void dark()
    {
        editor.selectedPayload.isDark = isDark.isSelected();
    }

    private void save()
    {
        if (door != null)
        {
            editor.updateDoor(door);
        }
    }

    public void update()
    {
        if (door != null)
        {
            if (door.crawl)
            {
                secLev.setSelectedIndex(11);
            }
            else
            {
                secLev.setSelectedIndex(door.getSecuritylevel());
            }
            objLev.setSelectedIndex(door.getObjectiveLevel());
            isDark.setSelected(door.isDark());
        }
        else
        {
            secLev.setSelectedIndex(0);
            objLev.setSelectedIndex(0);
            isDark.setSelected(false);
        }
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
