/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ItemPlacer.java
 *
 * Created on Jun 17, 2012, 3:51:35 PM
 */

package LevelEditor;

/**
 *
 * @author Jim
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JLabel;

public class ItemPlacer extends javax.swing.JPanel
{

    private Editor editor;
    private JComboBox items;
    private JComboBox rank;
    private JLabel label;
    private JLabel label2;

    /** Creates new form ItemPlacer */
    public ItemPlacer(Editor e)
    {
        initComponents();
        this.setLayout(null);
        this.setSize(400, 300);
        editor = e;

        items = new JComboBox(editor.items);
        this.add(items);
        items.setBounds(0, 40, 200, 50);

        items.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent e)
            {
                updateItem();
            }
        });

        label = new JLabel("Select an Item to add:");
        this.add(label);
        label.setBounds(0, 0, 150, 50);

        label2 = new JLabel("Rank:");
        this.add(label2);
        label2.setBounds(220, 0, 50, 50);

        Integer[] ranks = {1,2,3};
        rank = new JComboBox(ranks);
        this.add(rank);
        rank.setBounds(220, 40, 80, 50);
        this.setVisible(true);

        items.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent e)
            {
                updateItem();
            }
        });

        rank.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent e)
            {
                updateItem();
            }
        });

    }

    private void updateItem()
    {
        editor.selectedPayload.itemID = items.getSelectedIndex();
        editor.selectedPayload.rank = rank.getSelectedIndex() + 1;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
