/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LevelSettingsEditor.java
 *
 * Created on Jun 30, 2012, 8:19:34 PM
 */

package LevelEditor;

/**
 *
 * @author Jim
 */

import javax.swing.JLabel;

public class LevelSettingsEditor extends javax.swing.JPanel
{
    private Editor editor;
    private JLabel sx;
    private JLabel sy;

    /** Creates new form LevelSettingsEditor */
    public LevelSettingsEditor(Editor e)
    {
        initComponents();
        editor = e;
        this.setLayout(null);
        this.setSize(400, 300);

        JLabel l1 = new JLabel("Level Settings - Starting Position:");
        this.add(l1);
        l1.setBounds(0, 0, 250, 50);

        JLabel l2 = new JLabel("Start X = ");
        this.add(l2);
        l2.setBounds(0, 50, 55, 20);

        JLabel l3 = new JLabel("Start Y = ");
        this.add(l3);
        l3.setBounds(0, 70, 55, 20);

        JLabel l4 = new JLabel("Click on a location anywhere to set the start position.");
        this.add(l4);
        l4.setBounds(0, 150, 400, 20);

        JLabel l5 = new JLabel("The starting position must occur on room index 0.");
        this.add(l5);
        l5.setBounds(0, 170, 400, 20);
        
        sx = new JLabel("1");
        this.add(sx);
        sx.setBounds(53, 50, 250, 20);

        sy = new JLabel("1");
        this.add(sy);
        sy.setBounds(53, 70, 250, 20);
    }

    public void update()
    {
        sx.setText("" + editor.currLevel.getStartX());
        sy.setText("" + editor.currLevel.getStartY());
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
