/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlayerPathPlacer.java
 *
 * Created on Nov 29, 2013, 1:25:08 PM
 */

package LevelEditor;

/**
 *
 * @author Jim
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.ScrollPaneConstants;

public class PlayerPathPlacer extends javax.swing.JPanel
{
    private Editor editor;
    public Path path;
    private JTextArea pathTA;
    private JButton save;

    /** Creates new form PlayerPathPlacer */
    public PlayerPathPlacer(Editor e)
    {
        initComponents();
        editor = e;
        this.setLayout(null);
        this.setSize(400, 300);

        JLabel l1 = new JLabel("Player Path");
        this.add(l1);
        l1.setBounds(0, 0, 100, 50);

        pathTA = new JTextArea("");

        pathTA.setAutoscrolls(true);
        pathTA.setEditable(true);

        JScrollPane jsp = new JScrollPane(pathTA);
        jsp.setBounds(0, 50, 300, 200);
        jsp.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        this.add(jsp);

        save = new JButton("Save Changes");
        this.add(save);
        save.setBounds(0, 260, 150, 40);

        JButton help = new JButton("?");
        this.add(help);
        help.setBounds(250, 260, 50, 30);

        save.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent e)
            {
                saveChanges();
            }
        });

        help.addActionListener(new ActionListener()
        {
           public void actionPerformed(ActionEvent e)
           {
                dispHelp();
           }
        });
    }

    private void dispHelp()
    {
        String message = "To use the Player Path editor, the following format must be strictly adhered to:\nX-Coordinate[space]Y-Coordinate[space]DIRECTION[space]BEHAVIOR\n"
                + "\nAcceptable Directions include:\nUP, DOWN, LEFT, RIGHT\n\nAcceptable Behaviors include:\nCONTINUE, STOP, WAIT_AND_CONTINUE, LONG_WAIT_AND_CONTINUE\n\n"
                + "Example Path:\n10 5 RIGHT CONTINUE\n15 5 DOWN WAIT_AND_CONTINUE\n15 12 LEFT STOP\n\nPlease note that if one waypoint is heading LEFT or RIGHT, then the Y-Coordinate\nof the following waypoint must match the current waypoint's Y-Coordinate.\n"
                + "The same is true for waypoints heading UP or DOWN, but with X-Coordinates.";
        JOptionPane.showMessageDialog(this, message, "Using Player Path Editor", JOptionPane.QUESTION_MESSAGE);
    }

    private void saveChanges()
    {        
        editor.selectedPayload.path = pathTA.getText();
        editor.updatePlayerPath();
    }
    
    public void updatePath(Path p)
    {
        if (p != null)
        {
            pathTA.setText(p.toString());
            path = p;
        }
        else
        {
            pathTA.setText("");
            path = null;
        }
    }

    //This resets everything and allows functionality to persist post-editing
    public void clearPathText()
    {
        pathTA.setText("");
        path = null;
        editor.selectedPayload.path = "";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
