/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TileSelector.java
 *
 * Created on Jun 3, 2012, 10:01:04 PM
 */

package LevelEditor;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author Jim
 */
public class TileSelector extends javax.swing.JPanel
{
    private Editor editor;
    private JComboBox tiles;
    private JLabel label;
    private JLabel label2;

    /** Creates new form TileSelector */
    public TileSelector(Editor e)
    {
        initComponents();
        this.setLayout(null);
        this.setSize(400, 300);
        editor = e;

        tiles = new JComboBox(editor.images);
        this.add(tiles);
        tiles.setBounds(0, 40, 200, 50);
        this.setVisible(true);

        tiles.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent e)
            {
                updateTile();
            }
        });

        label = new JLabel("Select Tile:");
        label2 = new JLabel("[!] A leading asterix * denotes a wall tile.");
        this.add(label);
        this.add(label2);
        label.setBounds(0, 0, 100, 40);
        label2.setBounds(0, 90, 400, 40);

    }

    private void updateTile()
    {
        editor.selectedPayload.id = tiles.getSelectedIndex();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
